### ISSUE TITLE
Step 1 createDid.js not working

### ISSUE THREAD

**Issue by tzven0** [adrian-grassl/iota-identity-tutorial#1]
Hello,

in advance, thanks for the effort of providing this tutorial. Sadly, i don't even get it to run past the first step. I cloned the repository and installed the dev version of the package via npm. After a call to createDid.js, which is to produce the .json files inside weakhold, i do get:

```$node .\createDid.js
C:\Users\svenc\dev\iota-identity-tutorial\node_modules\@iota\identity-wasm\node\identity_wasm.js:224
        throw new Error(`expected instance of ${klass.name}`);
              ^

Error: expected instance of KeyPair
    at _assertClass (C:\Users\svenc\dev\iota-identity-tutorial\node_modules\@iota\identity-wasm\node\identity_wasm.js:224:15)
    at new Document (C:\Users\svenc\dev\iota-identity-tutorial\node_modules\@iota\identity-wasm\node\identity_wasm.js:1898:13)
    at createDid (C:\Users\svenc\dev\iota-identity-tutorial\createDid.js:17:26)
    at Object.<anonymous> (C:\Users\svenc\dev\iota-identity-tutorial\createDid.js:45:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

It seems that the argument for Document KeyType.Ed25519 is not of KeyPair. Therefore the assert in the constructor fails. What did i miss? I initially thought, that the Document will also create the KeyPair.

.js Noob here btw...

Thanks!

**Comment by tzven0** [comment]
I just found this, which should be missing in your files: https://github.com/iotaledger/identity.rs/blob/main/bindings/wasm/examples/src/create_did.js#L17
